application: xmpptest
version: 1
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: .*
  script: xmpptest.py
