application: jnoraky
version: 3
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /delete
  script: ModelUploader.py

- url: /fiducial
  script: ModelUploader.py
  login: admin

- url: /fiducialupload
  script: ModelUploader.py
  login: admin

- url: /.*
  script: ModelUploader.py
  