application: capabilities
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: .*
  script: main.py
