application: pipeline-test
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on

handlers:
- url: /_ah/pipeline(/.*)?
  script: pipeline/handlers.py

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /static
  static_dir: static

- url: .*
  login: required
  script: main.py
